export const INCREMENT= 'INCREMENT'
 export const DECREMENT = 'DECREMENT'
 export const CHANGE = 'CHANGE'
 export const ADD_TO_CART='ADD_TO_CART'
 export const REMOVE_FROM_CART= 'REMOVE_FROM_CART'

 export const ADD_TO_FAVOURITE= 'ADD_TO_FAVOURITE'

 export const REMOVE_FROM_FAVOURITE= 'REMOVE_FROM_FAVOURITE'


 export const CHANGE_DARK_MOODE= 'CHANGE_DARK_MOODE'
